config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  use_doorkeeper do
    controllers applications: 'oauth/applications',
    authorized_applications: 'oauth/authorized_applications'
  end

  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end
  resources :devices
  resources :teams
  resources :organisations, :academia, :events

  if Setting.has_module?(:home)
    root to: 'recommendations#index'
  else
    root to: 'topics#index'
  end
  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/]+/i
  }

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind', to: 'users#auth_unbind', as: 'unbind_account'

  mount RuCaptcha::Engine, at: '/rucaptcha'
  mount Notifications::Engine, at: '/notifications'
  mount StatusPage::Engine, at: '/'

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id', to: 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed', to: 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last', to: 'topics#recent', as: 'recent_topics'

  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :favorites
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search', to: 'search#index', as: 'search'
  get '/search/users', to: 'search#users', as: 'search_users'
  get '/search/keywords', to: 'search#keywords', as: 'search_keywords'

  namespace :wechat do
    root to: 'recommendations#index', as: 'root'
    get '/acquaint', to: 'mine#acquaint'
    get '/friend', to: 'mine#friend'
    get '/send_friend_request', to: 'mine#send_friend_request'
    get '/me', to: 'mine#welcome'
    resources :nodes do
      get resources :topics
      collection do
        get :time_more
        get :circle_more
        get :find_circle
        get :focus
        get :application_notice
        get :deal_apply
      end
    end
    resources :invites do
      collection do
        get :share
      end
    end
    resources :orders do
      collection do 
        post :notify
      end
    end
    get '/search', to: 'search#index', as: 'search'
    resources :recommendations
    resources :passages do
      resources :comments
    end
    resources :topics do
      collection do
        get :welcome
        get :follow_tag
        get :collect_tag
      end
    end
    resources :friendships, :friend_requests
    constraints(id: /#{User::LOGIN_FORMAT}*/) do
    resources :users, path: '' do
      collection do
        post :speciality
      end
      resources :friendships, :friend_requests
      resources :passages do
        member do
          get :close
        end
      end

    end
  end
end
namespace :admin do
  root to: 'home#index', as: 'root'
  resources :site_configs
  resources :replies
  resources :topics do
    resources :messages
    member do
      post :suggest
      post :unsuggest
      post :undestroy
      get :push
    end
  end
  resources :messages do
    collection do
      get :today_action
    end
  end
  resources :nodes do
    member do 
      get :review
    end
  end
  resources :sections
  resources :friend_requests
  resources :users do
    member do
      delete :clean
      get :friends
    end
  end
  resources :photos
  resources :pages do
    resources :versions, controller: :page_versions do
      member do
        post :revert
      end
    end
  end
  resources :comments
  resources :site_nodes
  resources :sites do
    member do
      post :undestroy
    end
  end
  resources :locations
  resources :exception_logs do
    collection do
      post :clean
    end
  end
  resources :applications
  resources :organisations, :events, :keywords, :shares, :passages
  resources :academia do
    collection do
      post :import
    end
  end
end

get 'api', to: 'home#api', as: 'api'
get 'markdown', to: 'home#markdown', as: 'markdown'
get 'keywords', to: 'home#keywords'
resources :recommendations
namespace :api do
  namespace :v3 do
    get 'hello', to: 'root#hello'

    resource :devices
    resource :likes
    resources :nodes
    resources :photos
    resources :organisations
    resources :academia
    resources :notifications do
      collection do
        post :read
        get :unread_count
        delete :all
      end
    end
    resources :topics do
      member do
        post :update
        get :replies
        post :replies
        post :follow
        post :unfollow
        post :favorite
        post :unfavorite
        post :ban
        post :action
      end
    end
    resources :replies do
      member do
        post :update
      end
    end
    resources :users do
      collection do
        get :me
      end
      member do
        get :topics
        get :replies
        get :favorites
        get :followers
        get :following
        get :blocked
        post :follow
        post :unfollow
        post :block
        post :unblock
      end
    end

    match '*path', to: 'root#not_found', via: :all
  end
end

authenticate :user, ->(u) { u.admin? } do
  mount Sidekiq::Web, at: '/sidekiq'
  mount PgHero::Engine, at: "pghero"
end

mount JasmineRails::Engine, at: '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get 'users/city/:id', to: 'users#city', as: 'location_users'
  get 'users', to: 'users#index', as: 'users'

  constraints(id: /#{User::LOGIN_FORMAT}*/) do
  resources :users, path: '', as: 'users' do
    member do
        # User only
        get :topics
        get :replies
        get :events
        get :favorites
        get :notes
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :calendar
        get :friendships
        get :add_friend
        
      end

      resources :team_users, path: 'people' do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match '*path', to: 'home#error_404', via: :all
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < Admin::ApplicationController
    before_action :set_topic, only: [:show, :edit, :update, :destroy, :undestroy, :suggest, :unsuggest, :push]

    def index
      @topics = Topic.unscoped.order(id: :desc)
      @topics = @topics.paginate(page: params[:page], per_page: 30)
    end

    def show
    end

    def new
      @topic = Topic.new
    end

    def edit
    end

    def create
      @topic = Topic.new(params[:topic].permit!)

      if @topic.save
        redirect_to(admin_topics_path, notice: 'Topic was successfully created.')
      else
        render action: 'new'
      end
    end

    def update
      if @topic.update_attributes(params[:topic].permit!)
        redirect_to(admin_topics_path, notice: 'Topic was successfully updated.')
      else
        render action: 'edit'
      end
    end

    def destroy
      @topic.destroy_by(current_user)

      redirect_to(admin_topics_path)
    end

    def undestroy
      @topic.update_attribute(:deleted_at, nil)
      redirect_to(admin_topics_path)
    end

    def suggest
      @topic.update_attribute(:suggested_at, Time.now)
      redirect_to(@topic, notice: "Topic:#{params[:id]} suggested.")
    end

    def unsuggest
      @topic.update_attribute(:suggested_at, nil)
      redirect_to(@topic, notice: "Topic:#{params[:id]} unsuggested.")
    end

    def push
      link = "#{Setting.domain}#{topic_path(@topic)}"
      if Message.send_single_message(@topic, current_user.id, link)
        redirect_to(admin_topics_path, notice: "推送成功.")
      else
        redirect_to(admin_topics_path, notice: "推送失败.")
      end
    end

    private

    def set_topic
      @topic = Topic.unscoped.find(params[:id])
    end
  end
end

app/controllers/wechat/topics_controller.rb
module Wechat
  class TopicsController < Wechat::BaseController
     
    def welcome    
      if current_user.interest
        @items = Search.user_interest_query(current_user.interest).first(5)
      end
      @keywords = Keyword.get_hot
      @topics = Topic.last_actived.without_suggest
      @topics =
        if current_user
          @topics.without_nodes(current_user.blocked_node_ids)
            .without_users(current_user.blocked_user_ids)
        else
          @topics.without_hide_nodes
        end
      @topics = @topics.fields_for_list
      @topics = @topics.paginate(page: params[:page], per_page: 5, total_entries: 1500).to_a
      @page_title = t('menu.topics')
      fresh_when([@topics])         
    end 
    
    def follow_tag
      if params[:q].kind_of?(Array)
        query = params[:q].join(",")
        current_user.update_attributes(interest: query)
      end
    end 
     
    def collect_tag
      if params[:q].present?
        if current_user.interest.length > 0
          current_interest = "#{current_user.interest}" +"," + "#{params[:q].to_s}"
          current_user.update_attributes(interest: current_interest)
        else
          current_user.update_attributes(interest: params[:q].to_s)
        end
        Keyword.set_interest(current_user, params[:q].to_s)
      end
      redirect_to welcome_wechat_topics_url
    end 
     
    def index
      # 从圈子详情页进来
      if params[:node_id] 
        if current_user.nil?
          redirect_to new_user_session_url
        else
          access_level=Node.find(params[:node_id].to_i).access_level
          #当前用户关注的圈子
          node_ids=current_user.node_ids 
          # 没有加入半公开的
          if access_level==Node.accesses[:semi_public] && !node_ids.include?(params[:node_id].to_i)
            #只显示三条
            @topics=Topic.where(:node_id=> params[:node_id]).order(created_at: :desc).limit(3)
            params[:info]="非圈子成员中查看三篇文章"
            @topics=@topics.paginate(page: params[:page],per_page:3)
          # 如果是公开的圈子,或者已经加入的私密的圈子,或者加入半公开的圈子
          elsif access_level==Node.accesses[:open] || ((access_level==Node.accesses[:secretive] || access_level==Node.accesses[:semi_public])&& node_ids.include?(params[:node_id].to_i)) 
            @topics=Topic.where(:node_id=> params[:node_id]).order(created_at: :desc)
            params[:info]="本圈子下共有#{@topics.size}篇文章"
            @topics=@topics.paginate(page: params[:page],per_page:30)
          #url被篡改
          else 
            redirect_to find_circle_wechat_nodes_url
          end
        end
      else #从资讯进来
        params[:info]="最新资讯"
        @topics=Topic.all.select{|topic| topic.recommendation==true || topic.node.section.name != '圈子' }
        # @topics = Topic.last_actived.without_suggest
        # @topics =
        # if current_user
        #   @topics.without_nodes(current_user.blocked_node_ids)
        #   .without_users(current_user.blocked_user_ids)
        # else
        #   @topics.without_hide_nodes
        # end
        # @topics = @topics.fields_for_list
        @topics = @topics.paginate(page: params[:page], per_page: 30)
        @page_title = t('menu.topics')
        fresh_when([@topics])
      end
    end
     
    def show
      @topic = Topic.unscoped.find(params[:id])
      #用户没有关注 文章所在的圈子,并且该圈子是私密的或者是半公开的,则不能访问此文章
      redirect_to find_circle_wechat_nodes_url if !current_user.node_ids.include?(@topic.node_id) && (@topic.node.access_level ==Node.accesses[:secretive] || @topic.node.access_level ==Node.accesses[:semi_public])
      render_404 if @topic.deleted?
      @topic.hits.incr(1)
      @node = @topic.node
      @show_raw = params[:raw] == '1'
      @can_reply = can? :create, Reply

      @replies = Reply.unscoped.where(topic_id: @topic.id).without_body.order(:id).all

       #check_current_user_liked_replies
       #check_current_user_status_for_topic
       #set_special_node_active_menu
      fresh_when([@topic, @node, @show_raw, @replies, @has_followed, @has_favorited, @can_reply])
    end

    def new
      @topic = Topic.new(user_id: current_user.id,node_id:params[:node_id])
    end

    def create
      @topic=Topic.new(topic_params)
      @topic.summary=@topic.body.to_s[0,15] if @topic.body.length>15
      @topic.user_id=current_user.id
      if @topic.save
        redirect_to(wechat_topic_url(@topic))
      else 
        redirect_to(new_wechat_topic_url(:node_id=>@topic.node.id),alert:"发表失败"+@topic.errors.full_messages.to_s)
      end
    end

    def topic_params
      params.require(:topic).permit(:title, :body, :node_id,:summary, :source, :tags)
    end

  end
end

app/helpers/topics_helper.rb
require 'digest/md5'
module TopicsHelper
  def topic_favorite_tag(topic, opts = {})
    return '' if current_user.blank?
    opts[:class] ||= ''
    class_name = ''
    link_title = '收藏'
    if current_user && current_user.favorite_topic_ids.include?(topic.id)
      class_name = 'active'
      link_title = '取消收藏'
    end

    icon = raw(content_tag('i', '', class: 'fa fa-bookmark'))
    if opts[:class].present?
      class_name += ' ' + opts[:class]
    end

    link_to(raw("#{icon} 收藏"), '#', title: link_title, class: "bookmark #{class_name}", 'data-id' => topic.id)
  end

  def topic_follow_tag(topic, opts = {})
    return '' if current_user.blank?
    return '' if topic.blank?
    return '' if owner?(topic)
    opts[:class] ||= ''
    class_name = 'follow'
    class_name += ' active' if topic.follower_ids.include?(current_user.id)
    if opts[:class].present?
      class_name += ' ' + opts[:class]
    end
    icon = content_tag('i', '', class: 'fa fa-eye')
    link_to(raw("#{icon} 关注"), '#', 'data-id' => topic.id, class: class_name)
  end

  def topic_title_tag(topic, opts = {})
    return t('topics.topic_was_deleted') if topic.blank?
    if opts[:reply]
      index = topic.floor_of_reply(opts[:reply])
      path = main_app.topic_path(topic, anchor: "reply#{index}")
    else
      path = main_app.topic_path(topic)
    end
    link_to(topic.title, path, title: topic.title)
  end

  def topic_excellent_tag(topic)
    return '' unless topic.excellent?
    content_tag(:i, '', title: '精华帖', class: 'fa fa-diamond', data: { toggle: 'tooltip' })
  end

  def topic_close_tag(topic)
    return '' unless topic.closed?
    content_tag(:i, '', title: '问题已解决／话题已结束讨论', class: 'fa fa-check', data: { toggle: 'tooltip' })
  end
end

app/views/topics/_buttons.html.erb
<div class="opts">
  <% if !turbolinks_ios? %>
    <%= likeable_tag(@topic) %>
    <%= topic_follow_tag(@topic) %>
    <%= topic_favorite_tag(@topic) %>
  <% end %>

  <% if admin? %>
    <% if !@topic.suggested_at.blank? %>
    <%= link_to raw("<i class='fa fa-angle-double-up'></i> 取消"), unsuggest_admin_topic_path(@topic), method: :post, remote: true %>
    <% else %>
    <%= link_to raw("<i class='fa fa-angle-double-up'></i> 置顶"), suggest_admin_topic_path(@topic), method: :post, remote: true %>
    <% end %>
    <% if !@topic.excellent? %>
    <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_topic_path(@topic.id, type: 'excellent'), title: "设为精华帖" , method: "post", remote: true %>
    <% end %>

    <% if @topic.node_id != Node.no_point.id %>
    <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), action_topic_path(@topic.id, type: 'ban'), method: 'post', remote: true, title: "屏蔽此贴，移动到 NoPoint 节点" %>
    <% end %>
  <% end %>
  <span class="pull-right opts">
    <% if owner?(@topic) or admin? %>
    <% if can?(:close, @topic) %>
      <% if !@topic.closed? %>
        <%= link_to raw("<i class='fa fa-check'></i>"), action_topic_path(@topic, type: 'close'), method: 'post', title: "关闭讨论／问题已解决", remote: true, data: { toggle: 'tooltip' } %>
      <% else %>
        <%= link_to raw("<i class='fa fa-undo'></i>"), action_topic_path(@topic, type: 'open'), method: 'post', title: "重新开启话题", remote: true, data: { toggle: 'tooltip' } %>
      <% end %>
    <% end %>
    <%= link_to "", edit_topic_path(@topic), class: "fa fa-pencil", title: "修改本帖" %>
      <% if can?(:destroy, @topic) %>
      <%= link_to "", topic_path(@topic.id), method: :delete, remote: true, 'data-confirm': t("common.confirm_delete"), class: "fa fa-trash", title: "删除本帖" %>
      <% end %>
    <% end %>
  </span>
</div>

app/views/topics/_editor_toolbar.html.erb
<div class="editor-toolbar">
  <div class="opts pull-right">
    <a href="#" class="pickup-emoji"><i class="fa fa-smile-o"></i></a>
    <span class="dropdown dropdown-small" id="editor-toolbar-insert-code">
      <a href="#editor-toolbar-insert-code" data-toggle="dropdown" title="<%= t("topics.insert_codes") %>" href="#editor-toolbar-insert-code"><i class="fa fa-code"></i></a>
      <ul class="dropdown-menu insert-codes" role="menu">
        <%= insert_code_menu_items_tag %>
      </ul>
    </span>
    <%= link_to(icon_tag("image"), "#", id: "topic-upload-image", rel: "twipsy", title: t("topics.add_image") )%>
  </div>
  <ul class="nav nav-pills" style="clear:none;">
    <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
    <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
  </ul>
</div>

app/views/topics/_related_topics.html.erb
<% cache([@topic, 'related_topic', Date.current]) do %>
  <% if @topic.related_topics.present? %>
    <div class="panel panel-default">
      <div class="panel-heading">相关话题</div>
      <ul class="list-group">
        <% @topic.related_topics.each do |topic| %>
          <li class="list-group-item"><%= link_to topic.title, topic %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/topics/_reply_form.html.erb
<%= render "editor_toolbar" %>
<%= form_for(Reply.new, remote: true, url: topic_replies_path(@topic)) do |f| %>

  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control", rows: "4", tabindex: "1" %>
  </div>
  <div class="submit-buttons">
    <button type="submit" id="reply-button" class="btn btn-primary" tabindex="2", data-disable-with='<%= t("topics.submit_reply") %>'><%= t("topics.submit_reply")%></button>
    <span class="help-inline" style="padding-left: 5px;" title="或者 Ctrl + Enter"><kbd>Command</kbd> + <kbd>Enter</kbd></span>

    <div class="pull-right"><a href="/markdown" target="_blank">排版说明</a></div>
  </div>
<% end %>

app/views/topics/_sidebar_for_topic_index.html.erb
<%= render 'shared/qr' %>
<% if can? :create, Topic %>
    <div class="panel panel-default clearfix">
      <div class="panel-body">
        <div class="btn-group btn-block pull-left">
          <%= link_to(t("topics.new_topic"), new_topic_path(node: params[:id]), class: "btn btn-primary" )%>
        </div>
      </div>
    </div>
<% end %>
<% if current_user && current_user.newbie? %>
<div class="panel panel-default">
  <div class="panel-heading">新手必读</div>
  <div class="panel-body">
    <%= raw Setting.newbie_notices %>
  </div>
</div>
<% end %>

<%= render "topics/sidebar_box_tips" %>

<%= raw Setting.topic_index_sidebar_html %>

<% cache(["sidebar_statistics",Time.now.strftime("%Y-%m-%d %H")]) do %>
<div class="panel panel-default">
  <div class="panel-heading"><%= t("common.statics")%></div>
  <ul class="list-group">
    <li class="list-group-item">社区会员: <%= User.unscoped.count %> 人</li>
    <li class="list-group-item">帖子数: <%= Topic.unscoped.count %> 个</li>
    <li class="list-group-item">回帖数: <%= Reply.unscoped.count %> 条</li>
  </ul>
</div>
<% end %>

app/views/topics/_topic_sidebar.html.erb
<div id="topic-sidebar" data-spy="affix" data-offset-bottom="65">
  <%= render 'shared/qr' %>
  <div class="panel panel-default">
    <div class="panel-body">
      <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
      <div class="buttons">
        <div class="group likes opts">
          <%= likeable_tag(@topic) %>
        </div>
        <div class="group">
          <div class="btn-group" role="group">
            <%= topic_follow_tag(@topic, class: 'btn btn-default') %>
            <%= topic_favorite_tag(@topic, class: 'btn btn-default') %>
          </div>
        </div>
      </div>
      <hr />
      <div class="group">
        <%= social_share_button_tag h("#{@topic.title} via: @#{Setting.twitter_id} ") %>
      </div>
      <hr />
      <div class="reply-buttons">
        <div class="total">
          共收到 <b><%= @topic.replies_count %></b> 条回复
        </div>
        <a href="#reply" class="btn btn-success btn-block btn-focus-reply">参与回复</a>
      </div>
      <hr />
      <div class="group opts">
        <% if admin? %>
          <div style="margin-bottom: 8px">
            <% if !@topic.suggested_at.blank? %>
            <%= link_to raw("<i class='fa fa-angle-double-up'></i> 取消"), unsuggest_admin_topic_path(@topic), method: :post, remote: true %>
            <% else %>
            <%= link_to raw("<i class='fa fa-angle-double-up'></i> 置顶"), suggest_admin_topic_path(@topic), method: :post, remote: true %>
            <% end %>
            <% if !@topic.excellent? %>
            <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_topic_path(@topic, type: 'excellent'), method: "post", remote: true %>
            <% end %>
            <% if @topic.node_id != Node.no_point.id %>
              <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), action_topic_path(@topic, type: 'ban'), method: 'post', title: "屏蔽此贴，移动到 NoPoint 节点", remote: true %>
            <% end %>
          </div>
        <% end %>

        <% if owner?(@topic) or admin? %>
        <div>
          <% if can?(:close, @topic) %>
            <% if !@topic.closed? %>
              <%= link_to raw("<i class='fa fa-check'></i> 结束"), action_topic_path(@topic, type: 'close'), method: 'post', title: "关闭讨论／问题已解决", remote: true, data: { toggle: 'tooltip' } %>
            <% else %>
              <%= link_to raw("<i class='fa fa-undo'></i> 开启"), action_topic_path(@topic, type: 'open'), method: 'post', title: "重新开启话题", remote: true, data: { toggle: 'tooltip' } %>
            <% end %>
          <% end %>
          <%= link_to raw('<i class="fa fa-pencil"></i> 编辑'), edit_topic_path(@topic), title: "修改本帖" %>
          <% if can?(:destroy, @topic) %>
            <%= link_to raw('<i class="fa fa-trash"></i> 删除'), topic_path(@topic.id), method: :delete, 'data-confirm' => t("common.confirm_delete"), title: "删除本帖", remote: true %>
          <% end %>
        </div>
        <% end %>
      </div>
      <a href="#" class="btn btn-block btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
    </div>
  </div>

  <div class="notify-updated">
    <a class="update" href="#"><i class="fa fa-bell-o"></i> <b>有新回复！</b>点击这里立即载入</a>
  </div>
</div>

app/views/topics/show.html.erb
<% title_tag @topic.title %>

<% content_for :scripts do %>
  <script type="text/javascript">
    Topics.topic_id = <%= @topic.id %>;
    <% if current_user && !@user_liked_reply_ids.blank? %>
    Topics.user_liked_reply_ids = [<%= @user_liked_reply_ids.join(",") %>];
    <% end %>
    $(document).ready(function(){
      <% if admin? %>
        $("#replies .reply a.edit").css('display','inline-block');
      <% elsif current_user %>
        $("#replies .reply a.edit[data-uid='<%= current_user.id %>']").css('display','inline-block');
      <% end %>
    })
  </script>
<% end %>

<div class="row">
  <div class="col-md-9">
    <div class="topic-detail panel panel-default">
      <%= render partial: "topics/topic_title", locals: { topic: @topic } %>
    
      <% if @topic.excellent? %>
      <div class="label-awesome">
        <i class="fa fa-diamond awesome"></i> 本帖已被设为精华帖！
        <% if admin? %>
        <div class="pull-right">
          <%= link_to icon_tag("close"), action_topic_path(@topic.id, type: 'unexcellent'), data: { method: "post", remote: true } %>
        </div>
        <% end %>
      </div>
      <% end %>
   
      

      <div class="panel-body markdown">
        <%= raw Setting.before_topic_html %>

        <article>
          <%= raw @topic.body_html %>
        </article>
        <% if @topic.author.present? %>
          源作者:
          <% JSON.parse(@topic.author).each do |key, value| %>
            <a href="<%= value %>" target="blank" ><%= key %></a>
          <% end %>
        <% end %>  
        <% if @topic.source_date.present? %>      
          发表日期: <%= @topic.source_date %>
        <% end %>
        <% if @topic.source.present?  && @topic.source =~ Regexp.new('www|http')%>
          <a href="<%= @topic.source %>" target="blank">原文链接</a>
        <% end %>
        <%= render 'shared/statement'%>
        <p>
          <% if @topic.tags.present? %>
          <i class="fa fa-tag fa-lg"></i>
            <% @topic.tags.split(",").each do |tag| %>
              <%= link_to tag, search_path(:q=> tag) %>
            <% end %>
          <% end %>
        </p>

        <%= raw Setting.after_topic_html %>
      </div>

      <div class="panel-footer clearfix">
        <%= render "buttons" %>
      </div>
    </div>

    <%= render partial: "ban_reason" %>

  <% if @replies.blank? %>
    <div class="no-result">
      <%= t("topics.no_replies") %>
    </div>
    <% else %>
    <div id="replies" class="panel panel-default" data-last-floor="<%= @replies.count(:all) %>">
      <div class="total panel-heading hide-ios">
        共收到 <b><%= @topic.replies_count %></b> 条评论
      </div>
      <div class="items panel-body">
        <%= cache([@topic, "raw:#{@show_raw}"]) do %>
          <%= render partial: "/replies/reply", collection: @replies %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if current_user %>
    <% if @topic.closed? %>
      <div class="alert alert-info">此话题已经于 <%= l @topic.closed_at, format: :long %> 关闭，不再接受任何评论。</div>
    <% else %>
      <div id="reply" class="panel panel-default">
        <div class="panel-heading hide-ios">评论</div>
        <div class="panel-body">
        <% if can? :create, Reply %>
          <%= render 'reply_form' %>
        <% else %>
          <div class="alert alert-info">
            当前设置新手用户不能在 22:00 ~ 9:00 发帖。
          </div>
        <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: "topics/translation/need_login_to_reply" %>
      </div>
    </div>
  <% end %>

  <%= render 'related_topics' %>
</div>

<% if !mobile? %>
  <div class="sidebar hidden-mobile col-md-3">
    <%= render 'topic_sidebar' %>
  </div>
<% else %>
  <div class="move-page-buttons">
    <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
    <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
  </div>
<% end %>
</div>