config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  use_doorkeeper do
    controllers applications: 'oauth/applications',
    authorized_applications: 'oauth/authorized_applications'
  end

  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end
  resources :devices
  resources :teams
  resources :organisations, :academia, :events

  if Setting.has_module?(:home)
    root to: 'recommendations#index'
  else
    root to: 'topics#index'
  end
  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/]+/i
  }

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind', to: 'users#auth_unbind', as: 'unbind_account'

  mount RuCaptcha::Engine, at: '/rucaptcha'
  mount Notifications::Engine, at: '/notifications'
  mount StatusPage::Engine, at: '/'

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id', to: 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed', to: 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last', to: 'topics#recent', as: 'recent_topics'

  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :favorites
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search', to: 'search#index', as: 'search'
  get '/search/users', to: 'search#users', as: 'search_users'
  get '/search/keywords', to: 'search#keywords', as: 'search_keywords'

  namespace :wechat do
    root to: 'recommendations#index', as: 'root'
    get '/acquaint', to: 'mine#acquaint'
    get '/friend', to: 'mine#friend'
    get '/send_friend_request', to: 'mine#send_friend_request'
    get '/me', to: 'mine#welcome'
    resources :nodes do
      get resources :topics
      collection do
        get :time_more
        get :circle_more
        get :find_circle
        get :focus
        get :application_notice
        get :deal_apply
      end
    end
    resources :invites do
      collection do
        get :share
      end
    end
    resources :orders do
      collection do 
        post :notify
      end
    end
    get '/search', to: 'search#index', as: 'search'
    resources :recommendations
    resources :passages do
      resources :comments
    end
    resources :topics do
      collection do
        get :welcome
        get :follow_tag
        get :collect_tag
      end
    end
    resources :friendships, :friend_requests
    constraints(id: /#{User::LOGIN_FORMAT}*/) do
    resources :users, path: '' do
      collection do
        post :speciality
      end
      resources :friendships, :friend_requests
      resources :passages do
        member do
          get :close
        end
      end

    end
  end
end
namespace :admin do
  root to: 'home#index', as: 'root'
  resources :site_configs
  resources :replies
  resources :topics do
    resources :messages
    member do
      post :suggest
      post :unsuggest
      post :undestroy
      get :push
    end
  end
  resources :messages do
    collection do
      get :today_action
    end
  end
  resources :nodes do
    member do 
      get :review
    end
  end
  resources :sections
  resources :friend_requests
  resources :users do
    member do
      delete :clean
      get :friends
    end
  end
  resources :photos
  resources :pages do
    resources :versions, controller: :page_versions do
      member do
        post :revert
      end
    end
  end
  resources :comments
  resources :site_nodes
  resources :sites do
    member do
      post :undestroy
    end
  end
  resources :locations
  resources :exception_logs do
    collection do
      post :clean
    end
  end
  resources :applications
  resources :organisations, :events, :keywords, :shares, :passages
  resources :academia do
    collection do
      post :import
    end
  end
end

get 'api', to: 'home#api', as: 'api'
get 'markdown', to: 'home#markdown', as: 'markdown'
get 'keywords', to: 'home#keywords'
resources :recommendations
namespace :api do
  namespace :v3 do
    get 'hello', to: 'root#hello'

    resource :devices
    resource :likes
    resources :nodes
    resources :photos
    resources :organisations
    resources :academia
    resources :notifications do
      collection do
        post :read
        get :unread_count
        delete :all
      end
    end
    resources :topics do
      member do
        post :update
        get :replies
        post :replies
        post :follow
        post :unfollow
        post :favorite
        post :unfavorite
        post :ban
        post :action
      end
    end
    resources :replies do
      member do
        post :update
      end
    end
    resources :users do
      collection do
        get :me
      end
      member do
        get :topics
        get :replies
        get :favorites
        get :followers
        get :following
        get :blocked
        post :follow
        post :unfollow
        post :block
        post :unblock
      end
    end

    match '*path', to: 'root#not_found', via: :all
  end
end

authenticate :user, ->(u) { u.admin? } do
  mount Sidekiq::Web, at: '/sidekiq'
  mount PgHero::Engine, at: "pghero"
end

mount JasmineRails::Engine, at: '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get 'users/city/:id', to: 'users#city', as: 'location_users'
  get 'users', to: 'users#index', as: 'users'

  constraints(id: /#{User::LOGIN_FORMAT}*/) do
  resources :users, path: '', as: 'users' do
    member do
        # User only
        get :topics
        get :replies
        get :events
        get :favorites
        get :notes
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :calendar
        get :friendships
        get :add_friend
        
      end

      resources :team_users, path: 'people' do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match '*path', to: 'home#error_404', via: :all
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < Admin::ApplicationController
    def index
      @recent_topics = Topic.recent.limit(5)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    share_link
    @excellent_topics = Topic.excellent.recent.fields_for_list.limit(20).to_a
    fresh_when([@excellent_topics, Setting.index_html])
  end
  
  def keywords
    @keywords = Keyword.all
  end

  def uploads
    # This is a temporary solution for help generate image thumb
    # that when you use :file upload_provider and you have no Nginx image_filter configurations.
    # DO NOT use this in production environment.
    format, version = params[:format].split("!")
    filename = "#{params[:path]}.#{format}"
    thumb = Homeland::ImageThumb.new(filename, version)
    send_file thumb.outpath, type: 'image/jpeg', disposition: 'inline'
  end

  def api
    redirect_to "/api-doc/"
  end

  def error_404
    render_404
  end

  def markdown
  end
end

app/views/home/index.html.erb
<%= raw Setting.index_html %>

<div class="home_suggest_topics panel panel-default">
  <div class="panel-heading">社区精华帖</div>
  <div class="panel-body topics row">
    <%
      odd_topics, even_topics = @excellent_topics.partition.each_with_index { |t, i| i.odd?  }
    %>
    <div class="col-md-6 topics-group">
      <%= render partial: "topics/topic", collection: odd_topics, locals: { suggest: false }, cached: -> (topic) { [topic, 'normal'] } %>
    </div>

    <div class="col-md-6 topics-group">
      <%= render partial: "topics/topic", collection: even_topics, locals: { suggest: false }, cached: -> (topic) { [topic, 'normal'] } %>
    </div>
  </div>
  <div class="panel-footer">
    <%= link_to "查看更多精华帖...", excellent_topics_path %>
  </div>
</div>

<% if !mobile? %>
  <%= render "/shared/index_sections" %>
  <%= render "/shared/hot_locations" %>
<% end %>

app/views/home/keywords.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        搜索关键词
      </div>
      <div class="panel-body">
        <div id="custom-search-input">
          <form action="/search" method="get" >
            <div class="input-group col-md-12">
              <input type="text" name="q" class="form-control input-lg" placeholder="焦点新闻／科技／企业／健康／体育赛事／娱乐" />
              <span class="input-group-btn">
                <button class="btn btn-info btn-lg" >
                  <i class="fa btn-search fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default userinfo">
      <div class="panel panel-heading">
        热门关键词
      </div>
      <div class="panel panel-body">
        <form action="/search" method="get">
        <% @keywords.each do |item| %>
          <div class="col-md-4">
            <div class="checkbox-inline">
            <input type="checkbox" name="q[]" value=<%= item.name %>><%= label_tag(:q, item.name) %></div>
          </div>
        <% end %>
        <div class="form-group pull-right">
          <button class="btn btn-info btn-lg" >
                  <i class="fa btn-search fa-search"></i>
                </button> </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/home/markdown.html.erb
<% title_tag 'Markdown 教程' %>

<% cache(['markdown-guide', Digest::MD5.hexdigest(Homeland::Markdown.example)]) do %>
<div class="panel markdown panel-default">
  <div class="panel-body">
    <h1>Markdown 教程</h1>
    <div class="row">
      <div class="col-md-6">
        <pre><code><%= Homeland::Markdown.example %></code></pre>
      </div>
      <div class="col-md-6">
        <%= markdown(Homeland::Markdown.example)%>
      </div>
    </div>
  </div>
</div>
<% end %>